name: Deploy to OVH

on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          npm install
          CI=false npm run build

      - name: Deploy to OVH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          rsync -avz -e "ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no" ./build/ kaflans@ssh.cluster023.hosting.ovh.net:/homez.148/kaflans/www/kafland
          rm -f /tmp/deploy_key